#!/bin/bash

f1=${1}
f2=${2}

f1TempHeaderlessSAM=.bamdiff_f1TempHeaderlessSAM
f2TempHeaderlessSAM=.bamdiff_f2TempHeaderlessSAM

samtools view ${f1} | sort > ${f1TempHeaderlessSAM}
samtools view ${f2} | sort > ${f2TempHeaderlessSAM}

diff ${f1TempHeaderlessSAM} ${f2TempHeaderlessSAM}

diffExitCode=$?

rm ${f1TempHeaderlessSAM}
rm ${f2TempHeaderlessSAM}

exit ${diffExitCode}

